---
#Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: SATIMGE Documentation
author: Energy Systems Research Group (ESRG)
logo: logo.png
html:
  theme: sphinx_rtd_theme
  theme_options:
    navigation_with_keys: True
    logo_only: True
    collapse_navigation: False
    display_version: False
    prev_next_buttons_location: 'bottom'
  use_issues_button: true
  use_repository_button: true
  use_repository_button: true

# Add extensions and configurations
extensions:
  - sphinx_rtd_theme

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: SatimTestBook.tex

# Add a bibtex file for citations
bibtex_bibfiles:
  - references.bib

# Repository information
repository:
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book update to: https://github.com/SavanhaJadedk/Satim-test-book-1.1/tree/Veda-Online-Documentation
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)
